dist: xenial

language:
  - php

php:
  - "7.3"
  - "7.2"
  - "5.6"

install:
  - composer install

script:
  - composer lint

branches:
  only:
  - master
  - develop

notifications:
  email: false

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
